language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
gemfile:
  - gemfiles/rails_30.gemfile
  - gemfiles/rails_31.gemfile
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_30.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_31.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_32.gemfile
